### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by Axkaban** [mindstorm12/vidbits#2]
They all look great! Just a small comment would be that you could save yourself from typing this a few times in different methods: [https://github.com/mindstorm12/vidbits/blob/master/routes/index.js#L75-L77](https://github.com/mindstorm12/vidbits/blob/master/routes/index.js#L75-L77)
By creating a building video function: 
```
const buildVideo = (video, {title, description, url}) => {
  video.title = title;
  video.description = description;
  video.url = url;

  video.validateSync();
};
```
As well, you could do the same with finding the video:
```
const findVideo = async (request) => {
  const {id} = request.params;

  return await Video.findOne({ _id: id });
}
```

**Comment by mindstorm12** [comment]
Thanks, will use this as I improve the project
